version: "3.9"
services:
    bot:
        build: .
        volumes:
            - .:/app:ro
            - ./otelcol-config.yml:/app/otelcol-config.yml:ro
            - ./otelcol-config-extras.yml:/app/otelcol-config-extras.yml:ro
        env_file: .env
        command: [ "--config=/app/otelcol-config.yml", "--config=/app/otelcol-config-extras.yml" ]
        ports:
            - "4317:4317"
            - "4318:4318"
            # Opening ports for OpenTelemetry collectors to work from container
            # Same is done in DFF Documentation, I just copied the ports
