version: "3.9"
services:
    bot:
        build:
            context: bot/
        volumes:
            - ./bot:/usr/src/app:ro
        environment:
            TG_BOT_TOKEN: /run/secrets/bot_token
        secrets:
            - bot_token
        expose:
            - "4317"
            - "4318"
            # Opening ports for OpenTelemetry instrumentors to work from container
            # About the same is done in DFF Documentation, I just copied the ports
secrets:
    bot_token:
        file: ./token.txt
